adminapp/urls.py
from django.urls import path


import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    # path('users/create/', adminapp.user_create, name='user_create'),
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),

    # path('users/read/', adminapp.users, name='users'),
    path('users/read/<page>/', adminapp.UsersListView.as_view(), name='users'),

    # path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),

    # path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    # path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),

    # path('categories/read/<page>/', adminapp.categories, name='categories'),
    path('categories/read/<page>/', adminapp.ProductCategoriesListView.as_view(), name='categories'),

    # path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),

    # path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),
    path('categories/delete/<int:pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    # path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),

    # path('products/read/category/<int:pk>/<page>', adminapp.products, name='products'),
    path('products/read/category/<int:pk>/<page>/', adminapp.ProductsListView.as_view(), name='products'),

    # path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),

    # path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),

    # path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),

    path('orders/read/<page>/', adminapp.OrdersListView.as_view(), name='orders'),

    # path('orders/read/<pk>/<status>/', adminapp.order_edit, name='order_edit'),
    path('orders/read/<pk>/<status>/', adminapp.OrderEditStatusView.as_view(), name='order_edit'),
]

authapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),

    path('edit/', authapp.edit, name='edit'),
    # path('edit/', authapp.UserEditUpdateView.as_view(), name='edit'),

    path('verify/<email>/<activation_key>/', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    # path('', basketapp.basket, name='basket'),
    path('', basketapp.BasketListView.as_view(), name='basket'),

    path('add/<pk>/', basketapp.basket_add, name='add'),

    # path('remove/<pk>/', basketapp.basket_remove, name='remove'),
    path('remove/<pk>/', basketapp.BasketDeleteView.as_view(), name='remove'),

    # path('edit/<int:pk>/<quantity>/', basketapp.edit, name='edit'),
    path('edit/<int:pk>/<quantity>/', basketapp.BasketUpdateView.as_view(), name='edit'),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

import mainapp.views as mainapp

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    # path('', mainapp.main, name='main'),
    path('', mainapp.MainListView.as_view(), name='main'),

    # path('about/', mainapp.about, name='about'),
    path('about/', mainapp.AboutTemplateView.as_view(), name='about'),

    # path('google7802449c7f174ab1.html/', mainapp.GoogleTemplateView.as_view(), name='google'),

    # path('service/', mainapp.service, name='service'),
    path('service/', mainapp.ServiceTemplateView.as_view(), name='service'),

    path('gallery/', include('mainapp.urls', namespace='gallery')),

    # path('news/', mainapp.news, name='news'),
    path('news/', mainapp.NewsTemplateView.as_view(), name='news'),

    # path('team/', mainapp.team, name='team'),
    path('team/', mainapp.TeamTemplateView.as_view(), name='team'),

    # path('contacts/', mainapp.contacts, name='contacts'),
    path('contacts/', mainapp.ContactsListView.as_view(), name='contacts'),

    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),

    path('', include('social_django.urls', namespace='social')),

    path('order/', include('ordersapp.urls', namespace='order')),

    path('admin/', include('adminapp.urls', namespace='admin')),
    # path('admin/', admin.site.urls, name='admin'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.views.decorators.cache import cache_page

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    # path('<page>/', mainapp.gallery, name='gallery_main'),
    path('<page>/', mainapp.GalleryListView.as_view(), name='gallery_main'),

    # path('category/<int:pk>/<page>/', mainapp.by_category, name='category'),
    path('category/<int:pk>/<page>/', mainapp.ByCategoryListView.as_view(), name='category'),

    # path('product/<str:pk>', mainapp.product, name='game'),
    path('product/<pk>/', mainapp.ProductDetailView.as_view(), name='game'),
    # path('product/<pk>/', cache_page(3600, key_prefix='geekshop')(mainapp.ProductDetailView.as_view()), name='game'),

    # path('category/<int:pk>/<page>/ajax/', cache_page(3600)(mainapp.product_ajax)),
]

ordersapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
import ordersapp.views as ordersapp


app_name = 'ordersapp'

urlpatterns = [
    path('', ordersapp.OrderListView.as_view(), name='orders_list'),
    path('create/', ordersapp.OrderItemsCreateView.as_view(), name='order_create'),
    path('read/<pk>/', ordersapp.OrderItemsReadView.as_view(), name='order_read'),
    path('update/<pk>/', ordersapp.OrderItemsUpdateView.as_view(), name='order_update'),
    path('delete/<pk>/', ordersapp.OrderItemsDeleteView.as_view(), name='order_delete'),
    path('forming/<pk>/', ordersapp.order_forming_complete, name='order_forming_complete'),
    path('create/edit/<int:pk>/<quantity>/', ordersapp.OrderUpdateView.as_view(), name='order_edit'),

    path('product/<pk>/price/', ordersapp.get_product_price_quantity),
]

mainapp/views.py
import random

from django.contrib.auth.decorators import user_passes_test
from django.core.cache import cache

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import DetailView, ListView
from django.views.generic.base import View, ContextMixin, TemplateView
from django.template.loader import render_to_string
from basketapp.models import Basket
from geekshop import settings
from mainapp.models import Games, Contacts, DiscountGames, GameCategories

from smssend import main as send_alert


def get_hot_product():
    games_list = Games.objects.all().exclude(quantity=0)
    if games_list:
        return random.sample(list(games_list), 1)[0]
    else:
        return None


def get_required_obj(lst, num, max_num=0):
    my_list = []
    i = 1
    while i <= num:
        rand_num = random.randint(0, len(lst) - 1)
        my_list.append(lst.pop(rand_num))
        i += 1
        if i == max_num + 1 and max_num != 0:
            break
    return my_list


class MainListView(ListView):
    model = Games
    template_name = 'mainapp/index.html'

    # @method_decorator(cache_page(3600))
    # def dispatch(self, *args, **kwargs):
    #     return super(MainListView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        result_list = list(Games.objects.all().select_related())[:4]
        # game_list = list(Games.objects.all().select_related())
        # result_list = get_required_obj(game_list, 4)
        # send_alert()
        return result_list

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'главная'
        context_data['css_file'] = 'style-index.css'
        context_data['contact_data'] = Contacts.objects.all()[0]

        return context_data


class AboutTemplateView(TemplateView):
    template_name = 'mainapp/about.html'

    @method_decorator(cache_page(3600))
    def dispatch(self, *args, **kwargs):
        return super(AboutTemplateView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'о нас'
        context_data['css_file'] = 'style-gallery.css'
        return context_data


class ServiceTemplateView(TemplateView):
    template_name = 'mainapp/services.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'услуги'
        context_data['css_file'] = 'style-gallery.css'
        return context_data


class GalleryListView(ListView):
    model = Games
    template_name = 'adminapp/games_list.html'
    paginate_by = 4

    def get_queryset(self):
        global hot_product
        hot_product = get_hot_product()
        if hot_product:
            rest_games = Games.objects.all().exclude(pk=hot_product.pk)
            return rest_games
        else:
            return Games.objects.all()

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'галлерея'
        context_data['css_file'] = 'style-gallery.css'
        if hot_product:
            context_data['hot_product'] = hot_product
        context_data['links_menu'] = GameCategories.objects.all()
        # context_data['links_menu'] = get_links_menu()
        context_data['games_discount'] = DiscountGames.objects.all()
        return context_data


class ByCategoryListView(ListView):
    model = Games
    template_name = 'mainapp/games_by_category.html'
    paginate_by = 4

    def get_queryset(self):
        category_pk = self.kwargs.get('pk', None)
        if category_pk:
            games_by_category = Games.objects.filter(game_category=category_pk)
        else:
            games_by_category = Games.objects.all()
        return games_by_category

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'категории'
        context_data['css_file'] = 'style-gallery.css'
        category_pk = self.kwargs.get('pk', None)
        if category_pk == 0:
            context_data['category'] = {'name': 'все', 'pk': category_pk}
        else:
            context_data['category'] = get_object_or_404(GameCategories, pk=category_pk)
        context_data['links_menu'] = GameCategories.objects.all()
        # context_data['links_menu'] = get_links_menu()
        hot_product = get_hot_product()
        if hot_product:
            context_data['hot_product'] = hot_product
        context_data['games_discount'] = DiscountGames.objects.all()
        return context_data


class NewsTemplateView(TemplateView):

    template_name = 'mainapp/news.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'новости'
        context_data['css_file'] = 'style-gallery.css'
        return context_data


class TeamTemplateView(TemplateView):
    template_name = 'mainapp/team.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'сотрудники'
        context_data['css_file'] = 'style-gallery.css'
        return context_data


class ContactsListView(ListView):
    model = Contacts
    template_name = 'mainapp/contacts.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['contact_data'] = Contacts.objects.all()[0]
        context_data['title'] = 'контакты'
        context_data['css_file'] = 'style-gallery.css'
        return context_data


class ProductDetailView(DetailView):
    model = Games

    # def get_object(self, queryset=None):
    #     self.object = super().get_object()
    #     item_pk = self.object.pk
    #     self.object = get_product(item_pk)
    #     return self.object

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        game_pk = self.kwargs.get('pk', None)
        category = Games.objects.get(pk=game_pk).game_category.pk
        context_data['object_list'] = Games.objects.filter(game_category=category).exclude(pk=game_pk).order_by('?')[:4]
        context_data['title'] = 'товары'
        context_data['css_file'] = 'style-product-page.css'
        context_data['contact_data'] = Contacts.objects.get(pk=1)
        return context_data


# def get_links_menu():
#     if settings.LOW_CACHE:
#         key = 'links_menu'
#         links_menu = cache.get(key)
#         if links_menu is None:
#             links_menu = GameCategories.objects.filter(is_active=True)
#             cache.set(key, links_menu)
#         return links_menu
#     else:
#         return GameCategories.objects.filter(is_active=True)
#
# def get_category(pk):
#     if settings.LOW_CACHE:
#         key = f'category_{pk}'
#         category = cache.get(key)
#         if category is None:
#             category = get_object_or_404(GameCategories, pk=pk)
#             cache.set(key, category)
#         return category
#     else:
#         return get_object_or_404(GameCategories, pk=pk)
#
# def get_products():
#     if settings.LOW_CACHE:
#         key = 'products'
#         products = cache.get(key)
#         if products is None:
#             products = Games.objects.all()
#             cache.set(key, products)
#         return products
#     else:
#         return Games.objects.all()
#
# def get_products_by_category(pk):
#     if settings.LOW_CACHE:
#         key = f'products_by_category_{pk}'
#         products_by_category = cache.get(key)
#         if products_by_category is None:
#             products_by_category = Games.objects.filter(game_category=pk)
#             cache.set(key, products_by_category)
#         return products_by_category
#     else:
#         return Games.objects.filter(game_category=pk)
#
# def get_product(pk):
#     if settings.LOW_CACHE:
#         key = f'product_{pk}'
#         product = cache.get(key)
#         if product is None:
#             product = Games.objects.get(pk=pk)
#             cache.set(key, product)
#         return product
#     else:
#         return Games.objects.get(pk=pk)
#
# def get_hot_product():
#     if settings.LOW_CACHE:
#         key = 'hot_product'
#         hot_product = cache.get(key)
#         if hot_product is None:
#             games_list = Games.objects.all().exclude(quantity=0)
#             hot_product = random.sample(list(games_list), 1)[0]
#             cache.set(key, hot_product)
#         return hot_product
#     else:
#         games_list = Games.objects.all().exclude(quantity=0)
#         hot_product = random.sample(list(games_list), 1)[0]
#         return hot_product

# @cache_page(3600)
# def main(request, pk=None):
#
#     title = 'главная'
#
#     contact_data = Contacts.objects.get(pk=1)
#     game_list = list(Games.objects.all())
#     # result_list = get_required_obj(game_list, 4)
#     result_list = list(Games.objects.all().select_related())[:3]
#     content = {
#         'title': title,
#         'css_file': 'style-index.css',
#         'object_list': result_list,
#         'contact_data': contact_data,
#     }
#     return render(request, 'mainapp/index.html', content)

# def about(request):
#
#     title = 'о нас'
#
#     content = {
#         'title': title,
#         'css_file': 'style-gallery.css',
#     }
#

mainapp/templates/mainapp/includes/inc_about.html
{% load static %}
<div class="about">
    <div class="about-paragraph">
        <h3 class="about-header">About Us!</h3>
        <p class="about-text">Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit. Ut&nbsp;enim ad&nbsp;minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut&nbsp;aliquid ex&nbsp;ea&nbsp;commodi consequatur?<br><br>
        Quis autem vel eum iure reprehenderit qui in&nbsp;ea&nbsp;voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p>
    </div>
    <img class="about-image" src="{% static 'img/About_us/1.jpg' %}" alt="image">
</div>

mainapp/templates/mainapp/includes/inc_categories_game.html
<div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Категории
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <a class="dropdown-item" href="{% url 'gallery:category' 0 1 %}">Все</a>
      {% for link in links_menu %}
        <a class="dropdown-item" href="{% url 'gallery:category' link.pk 1 %}">
            {{ link.name }}</a>
      {% endfor %}
      </div>
</div>

mainapp/templates/mainapp/includes/inc_contacts.html
{% load static %}
<div class="contact">
    <div class="contact">
        <h3 class="contact-header" >Contact Us</h3>
        <div class="contact-content">
            <div class="contact-info">
                <h4 class="contact-subheader">Get in touch with us</h4>
                <p class="contact-text">{{ contact_data.description }}<br><br>
                    {{ contact_data.address }}<br><br>
                    Telephone: {{ contact_data.phone }}<br><br>
                    FAX: {{ contact_data.fax }}<br><br>
                    Email: <a href="#">{{ contact_data.email }}</a>
                </p>
            </div>
            <div class="contact-box">
                <form action="#">
                    <input class="contact-name" type="text" placeholder="Name">
                    <input class="contact-email" type="email" placeholder="Email">
                    <textarea class="contact-message" placeholder="Massege"></textarea>
                    <input class="contact-bottom" type="submit" value="SUBMIT">
                </form>
            </div>
            {% if request.resolver_match.namespace == 'gallery' or request.resolver_match.url_name == 'products' %}
                <div class="arrow">
				    <a href="#"><img src="{% static 'img/arrow.png' %}" alt="arrow"></a>
			    </div>
            {% endif %}
        </div>
    </div>
</div>

mainapp/templates/mainapp/includes/inc_headerline.html
{% load static %}
<div class="headerline">
    <a class="logo" href="#"><p class="word_1">Historical</p><p class="word_2">games</p></a>
    <div class="contacts">
        <img class="phone" src="{% static 'img/first_screen/phone.png' %}" alt="phone"><span class="phone-text">+123 456 7890</span>
        <img class="email" src="{% static 'img/first_screen/email.png' %}" alt="email"><span class="email-text">info@example.com</span>
        <input class="search" type="text" placeholder="Search">
        <div class="icon-search"><a href="#"><img src="{% static 'img/first_screen/search.png' %}" alt="search"></a></div>
    </div>
</div>

mainapp/templates/mainapp/includes/inc_hot_offer.html
{% load static %}
{% load my_tags %}

<span class="hot_offer">Горячее предложение!</span>
<ul class="hot_product">
    <li>
        <div class="name-game"><a href="{% url 'gallery:game' hot_product.pk %}">
            <img class="game_image" src="{{ hot_product.image|media_folder_products }}"  alt='{{ hot_product.name }}'></a>
            <div class="gallery-name-buy"><p>{{ hot_product.name }}</p></div>
            <div class="gallery-name-quantity"><p>Количество: {{ hot_product.quantity }}</p></div>
            <a href="{% url 'basket:add' hot_product.pk %}"><input class="gallery-buy" type="button" value="Buy"></a>
        </div>
    </li>
</ul>
<p>{{ hot_product.description }}</p>

mainapp/templates/mainapp/includes/inc_main_menu.html
{% load static %}
<ul class="menu">
    <li class="menu-list">
        <a href="{% url 'main' %}"
           {% if request.resolver_match.url_name == 'main' %}class="menu-link menu-link-active"
           {% else %}class="menu-link"{% endif %}>Home</a>
    </li>
    <li class="menu-list">
        <a href="{% url 'about' %}"
           {% if request.resolver_match.url_name == 'about' %}class="menu-link menu-link-active"
           {% else %}class="menu-link"{% endif %}>About</a>
    </li>
    <li class="menu-list">
        <a href="{% url 'service' %}"
           {% if request.resolver_match.url_name == 'service' %}class="menu-link menu-link-active"
           {% else %}class="menu-link"{% endif %}>Service</a>
    </li>
    <li class="menu-list">
        <a href="{% url 'gallery:gallery_main' 1 %}"
           {% if request.resolver_match.namespace == 'gallery' %}class="menu-link menu-link-active"
           {% else %}class="menu-link"{% endif %}>Gallery</a>
    </li>
    <li class="menu-list">
        <a href="{% url 'news' %}"
           {% if request.resolver_match.url_name == 'news' %}class="menu-link menu-link-active"
           {% else %}class="menu-link"{% endif %}>News</a>
    </li>
    <li class="menu-list">
        <a href="{% url 'team' %}"
           {% if request.resolver_match.url_name == 'team' %}class="menu-link menu-link-active"
           {% else %}class="menu-link"{% endif %}>Team</a>
    </li>
    <li class="menu-list">
        <a href="{% url 'contacts' %}"
           {% if request.resolver_match.url_name == 'contacts' %}class="menu-link menu-link-active"
           {% else %}class="menu-link"{% endif %}>Contact Us</a>
    </li>
    {% if user.is_authenticated %}
        <li class="menu-list">
            <div class="dropdown">
                <a class="dropdown-toggle menu-link" href="#" data-toggle="dropdown">
                    {% if user.first_name %}
                        {{ user.first_name }}
                    {% else %}
                        Пользователь
                    {% endif %}
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a class="menu-link" href="{% url 'auth:edit' %}">
                           Профиль
                        </a>
                    </li>
                    <li>
                        <a class="menu-link" href="{% url 'order:orders_list' %}">
                            Заказы
                        </a>
                    </li>
                </ul>
            </div>
        </li>
            {% if user.is_superuser %}
                <li class="menu-list">
                    <a href="{% url 'admin:users' 1 %}" class="menu-link">
                       админка
                    </a>
                </li>
            {% endif %}
        <li class="menu-list">
            <a href="{% url 'auth:logout' %}"
               class="menu-link">
                выход
            </a>
        </li>
    {% else %}
        <li class="menu-list">
            <a href="{% url 'auth:login' %}"
               class="menu-link">
                вход
            </a>
        </li>
    {% endif %}
    <li class="menu-list">
        <a href="{% url 'basket:basket' %}"
           class="menu-link basket">
            {% if basket %}
                {{ basket.0.get_total_cost_cached|floatformat:0 }} $
                ({{ basket.0.get_total_quantity_cached }} шт)
            {% endif %}
        </a>
    </li>
</ul>

mainapp/templates/mainapp/includes/inc_name_game.html
{% load static %}
{% load my_tags %}


<ul class="gallery-menu">
    {% for game in object_list %}
        <li>
            <div class="name-game"><a href="{% url 'gallery:game' game.pk %}">
                <img class="game_image" src="{{ game.image|media_folder_products }}"  alt='{{ game.name }}'></a>
                <div class="gallery-name-buy"><p>{{ game.name }}</p></div>
                <div class="gallery-name-quantity"><p>Количество: {{ game.quantity }}</p></div>
                {% if game.quantity %}
                    <a href="{% url 'basket:add' game.pk %}"><input class="gallery-buy" type="button" value="Buy"></a>
                {% endif %}
            </div>
        </li>
    {% endfor %}
</ul>

mainapp/templates/mainapp/includes/inc_news.html
{% load static %}
<div class="news clearfix">
    <h3 class="news-header">News & Events</h3>
    <div class="latest-news">
        <p class="headers-news headers-news-1">Latest News</p>
        <div class="one-news">
            <div class="news-date">
                <p class="day">15</p>
                <p class="month">June</p>
                <p class="year">2016</p>
            </div>
            <p class="name-news">Fugiat Quo Voluptas</p>
            <p class="text-news">Quis autem vel eum iure reprehenderit qui in ea voluptate
                velit esse.</p>
        </div>
        <div class="one-news">
            <div class="news-date">
                <p class="day">18</p>
                <p class="month">June</p>
                <p class="year">2016</p>
            </div>
            <p class="name-news">FugQui In Ea Voluptate</p>
            <p class="text-news">Quis autem vel eum iure reprehenderit qui in ea voluptate
                velit esse.</p>
        </div>
        <div class="one-news">
            <div class="news-date">
                <p class="day">20</p>
                <p class="month">June</p>
                <p class="year">2016</p>
            </div>
            <p class="name-news">Autem Vel Eum Iure</p>
            <p class="text-news">Quis autem vel eum iure reprehenderit qui in ea voluptate
                velit esse.</p>
        </div>
    </div>
    <div class="featured-events">
        <p class="headers-news">Featured Events</p>
        <p class="arrows"><a href="">&lt;</a> <a href="">&gt;</a></p>
        <p class="line-news"></p>
        <div class="featured-img">
            <img src="{% static 'img/block_7/3.jpg' %}" alt="image-news">
            <img src="{% static 'img/block_7/2.jpg' %}" alt="image-news">
            <img src="{% static 'img/block_7/1.jpg' %}" alt="image-news">
        </div>
        <div class="featured-parg">
            <p class="parg-header"><a href="#">−   Assumenda Est Cliche Reprehenderit</a></p>
            <p class="parg-text">Lorem Ipsum is&nbsp;simply dummy text of&nbsp;the printing and typesetting industry. Lorem Ipsum has been the industry&rsquo;s standard dummy text ever since the 1500s, when an&nbsp;unknown printer took a&nbsp;galley of&nbsp;type and scrambled it&nbsp;to&nbsp;make a&nbsp;type specimen book.</p>
        </div>
        <p class="parg-header-plus"><a href="#">+   Assumenda Est Cliche Reprehenderit</a></p>
        <p class="parg-header-plus"><a href="#">+   Assumenda Est Cliche Reprehenderit</a></p>
        <p class="parg-header-plus"><a href="#">+   Assumenda Est Cliche Reprehenderit</a></p>
    </div>
</div>

mainapp/templates/mainapp/includes/inc_product_list_content.html
{% load static %}

<div class="links clearfix">
    {% include 'mainapp/includes/inc_categories_game.html' %}
</div>

<div class="products_list">
    {% include 'mainapp/includes/inc_name_game.html' %}
</div>

mainapp/templates/mainapp/includes/inc_products_list_content.html
{% load static %}

<div class="links clearfix">
    {% include 'mainapp/includes/inc_categories_game.html' %}
</div>

<div class="products_list">
    {% include 'mainapp/includes/inc_name_game.html' %}
</div>