authapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),

    path('edit/', authapp.edit, name='edit'),
    # path('edit/', authapp.UserEditUpdateView.as_view(), name='edit'),

    path('verify/<email>/<activation_key>/', authapp.verify, name='verify'),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

import mainapp.views as mainapp

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    # path('', mainapp.main, name='main'),
    path('', mainapp.MainListView.as_view(), name='main'),

    # path('about/', mainapp.about, name='about'),
    path('about/', mainapp.AboutTemplateView.as_view(), name='about'),

    # path('google7802449c7f174ab1.html/', mainapp.GoogleTemplateView.as_view(), name='google'),

    # path('service/', mainapp.service, name='service'),
    path('service/', mainapp.ServiceTemplateView.as_view(), name='service'),

    path('gallery/', include('mainapp.urls', namespace='gallery')),

    # path('news/', mainapp.news, name='news'),
    path('news/', mainapp.NewsTemplateView.as_view(), name='news'),

    # path('team/', mainapp.team, name='team'),
    path('team/', mainapp.TeamTemplateView.as_view(), name='team'),

    # path('contacts/', mainapp.contacts, name='contacts'),
    path('contacts/', mainapp.ContactsListView.as_view(), name='contacts'),

    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),

    path('', include('social_django.urls', namespace='social')),

    path('order/', include('ordersapp.urls', namespace='order')),

    path('admin/', include('adminapp.urls', namespace='admin')),
    # path('admin/', admin.site.urls, name='admin'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

authapp/models.py
from datetime import timedelta

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.timezone import now


class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatars', blank=True, verbose_name='аватарка')
    age = models.PositiveSmallIntegerField(verbose_name='возраст', default=20)
    email = models.EmailField(max_length=150, unique=True)

    activation_key = models.CharField(max_length=128, blank=True)
    activation_key_expires = models.DateTimeField(default=(now() + timedelta(hours=48)))

    def is_activation_key_expired(self):
        if now() <= self.activation_key_expires:
            return False
        else:
            return True


class ShopUserProfile(models.Model):
    MALE = 'М'
    FEMALE = 'W'

    GENDER_CHOICES = (
        (MALE, 'М'),
        (FEMALE, 'Ж')
    )

    user = models.OneToOneField(ShopUser, unique=True, null=False, db_index=True, on_delete=models.CASCADE)
    tagline = models.CharField(max_length=128, blank=True, verbose_name='теги')
    about_me = models.TextField(blank=True, verbose_name='обо мне')
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True, verbose_name='пол')

    @receiver(post_save, sender=ShopUser)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            ShopUserProfile.objects.create(user=instance)

    @receiver(post_save, sender=ShopUser)
    def save_user_profile(sender, instance, **kwargs):
        instance.shopuserprofile.save()

authapp/forms.py
from django.contrib.auth import forms
import hashlib
from random import random

from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from authapp.models import ShopUser, ShopUserProfile


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = "form-control"
            field.help_text = ''


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2',
                  'email', 'avatar', 'age')

    def __init__(self, *args, **kwargs):
        super(ShopUserRegisterForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = "form-control"
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError('Вы слишком молоды!')
        if data > 100:
            raise forms.ValidationError('Ого, видимо кто-то выпил эликсир бессмертия!!!')
        return data

    def clean_first_name(self):
        data = self.cleaned_data['first_name']
        i = 0
        while i <= 9:
            if str(i) in data:
                raise forms.ValidationError('Имя должно содержать только буквы!!!')
            i += 1
        return data

    def save(self, **kwargs):
        user = super(ShopUserRegisterForm, self).save()
        user.is_active = False
        salt = hashlib.sha1(str(random()).encode('utf8')).hexdigest()[:6]
        user.activation_key = hashlib.sha1((user.email + salt).encode('utf8')).hexdigest()
        user.save()

        return user


class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'email', 'avatar', 'age')

    def __init__(self, *args, **kwargs):
        super(ShopUserEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = "form-control"
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

    def __str__(self):
        return self.fields['avatar']

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError('Вы слишком молоды!')
        if data > 100:
            raise forms.ValidationError('Ого, видимо кто-то выпил эликсир бессмертия!!!')
        return data

    def clean_first_name(self):
        data = self.cleaned_data['first_name']
        i = 0
        while i <= 9:
            if str(i) in data:
                raise forms.ValidationError('Имя должно содержать только буквы!!!')
            i += 1
        return data


class ShopUserProfileEditForm(forms.ModelForm):
    class Meta:
        model = ShopUserProfile
        fields = ('tagline', 'about_me', 'gender')

    def __init__(self, *args, **kwargs):
        super(ShopUserProfileEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = "form-control"
            field.help_text = ''





authapp/views.py
from smtplib import SMTPDataError
from typing import re

from django.conf import settings
from django.contrib import auth
from django.contrib.auth.decorators import user_passes_test, login_required
from django.core.mail import send_mail
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView

from authapp.forms import ShopUserLoginForm, ShopUserRegisterForm, ShopUserEditForm, ShopUserProfileEditForm
from authapp.models import ShopUser


def verify(request, email, activation_key):
    try:
        user = ShopUser.objects.get(email=email)
        if user.activation_key == activation_key and not user.is_activation_key_expired():
            user.is_active = True
            user.save()
            auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            print('активация прошла успешно')
        else:
            print(f'Ошибка активации пользователя: {email}')
        return render(request, "authapp/verification.html")
    except Exception as e:
        print(f'Ошибка активации пользователя: {e.args}')
        return HttpResponseRedirect(reverse('main'))


def send_verify_email(user):
    verify_link = reverse('auth:verify', args=[user.email, user.activation_key])
    subject = f'активация пользователя {user.username}'
    message = f'для подтверждения перейдите по ссылке: {settings.DOMAIN_NAME}{verify_link}'
    try:
        return send_mail(subject, message, settings.EMAIL_HOST_USER, [user.email], fail_silently=False)
    except SMTPDataError:
        pass


def login(request):

    title = "вход"

    next_url = request.GET.get('next', '')

    login_form = ShopUserLoginForm(data=request.POST)
    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            if 'next' in request.POST.keys():
                return HttpResponseRedirect(request.POST['next'])
            else:
                return HttpResponseRedirect(reverse('main'))
    from_register = request.session.get('register', None)
    conf_code = request.session.get('conf_code', None)
    email = request.session.get('email', None)
    if from_register:
        del request.session['register']
        del request.session['conf_code']
        del request.session['email']

    content = {
        'title': title,
        'login_form': login_form,
        'next': next_url,
        'from_register': from_register,
        'confirmation': conf_code,
        'pth': f'{settings.DOMAIN_NAME}{request.get_full_path()}{email}{conf_code}',
        'email': email
    }
    return render(request, 'authapp/login.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main'))


def register(request):

    title = 'регистрация'

    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            user = register_form.save()
            if send_verify_email(user):
                print('сообщение подтверждения отправлено')
                request.session['register'] = True
                user_name = request.POST['username']
                conf_code, email = [ShopUser.objects.get(username=user_name).activation_key, ShopUser.objects.get(username=user_name).email]
                request.session['conf_code'] = conf_code
                request.session['email'] = email

            else:
                print('ошибка отправки сообщения')
            return HttpResponseRedirect(reverse('auth:login'))

    else:
        register_form = ShopUserRegisterForm()
    content = {
        'title': title,
        'register_form': register_form,
    }
    return render(request, 'authapp/register.html', content)


# class UserEditUpdateView(UpdateView):
#     model = ShopUser
#     template_name = 'authapp/edit.html'
#     form_class = ShopUserEditForm
#
#     def get_context_data(self, **kwargs):
#         context_data = super().get_context_data(**kwargs)
#         context_data['title'] = 'редактирование'
#         return context_data


@login_required
@transaction.atomic()
def edit(request):

    title = 'редактирование'

    if request.method == "POST":
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)
        profile_form = ShopUserProfileEditForm(request.POST, instance=request.user.shopuserprofile)
        if edit_form.is_valid() and profile_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))
    else:
        edit_form = ShopUserEditForm(instance=request.user)
        profile_form = ShopUserProfileEditForm(instance=request.user.shopuserprofile)

    ava = request.user.avatar


    content = {
        'title': title,
        'edit_form': edit_form,
        'profile_form': profile_form,
        'avatar': ava
    }

    return render(request, 'authapp/edit.html', content)

authapp/templates/authapp/base.html
{% load static %}
{% load my_tags %}
<html lang="ru">
	<head>
		<meta charset="UTF-8">
		<title>
            {% block title %}
                {{ title|title }}
            {% endblock %}
        </title>
        <link rel="shortcut icon" href="">
        {% block css %}
            <link rel="stylesheet" type="text/css" href="{% static 'style/style-index.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'style/css/bootstrap.min.css' %}">
            <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&family=Roboto+Condensed:wght@300;400&display=swap" rel="stylesheet">
            <script src="https://kit.fontawesome.com/a92ddd463b.js" crossorigin="anonymous"></script>
            <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/png">
            <link rel="stylesheet" type="text/css" href="{% static 'style/css/bootstrap-social.css' %}" />

	    {% endblock %}
    </head>
	<body>
		<div class="container_form">
            {% block content %}
			{% endblock %}
        </div>
	</body>
</html>

authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% block content %}
{% load my_tags %}

    <form class="form-horizontal" action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <img src="{{ avatar|media_folder_users }}" alt="avatar">
    {{ edit_form.as_table }}
    {{ profile_form.as_table }}
    <br>
    <input class="form-control" type="submit" value="Сохранить">
    </form>
    <a class="btn btn-link" href="{% url 'main' %}">На главную</a>
{% endblock %}

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% block content %}
    {% if from_register %}
        Сообщение подтверждения отправлено.<br>
        Код подтверждения: {{ confirmation }}<br>
<!--        Ссылка для перехода: <a href="{% url 'authapp:verify' email  confirmation %}">{{ pth }}</a>-->
    {% endif %}
    <form class="form-horizontal" action="{% url 'auth:login' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% if next %}
        <input name="next" type="hidden" value="{{ next }}" />
    {% endif %}
    {{ login_form.as_p }}
    <br>
    <input class="form-control" type="submit" value="Вход">
    </form>
    <button class="'btn btn-outline-dark form-control">
        <a class="btn" href="{% url 'auth:register' %}">регистрация</a>
    </button>
    <a class="btn btn-block btn-social btn-vk" href="{% url 'social:begin' 'vk-oauth2' %}?next=/">
        <span class="fa fa-vk"></span>Войти через VK
    </a>
    <a class="btn btn-block btn-social btn-google" href="{% url 'social:begin' 'google-oauth2' %}?next=/">
        <span class="fa fa-google"></span> Войти через Google
    </a>
    <a class="btn btn-block btn-social btn-github" href="{% url 'social:begin' 'github' %}?next=/">
        <span class="fa fa-github"></span> Войти через Github
    </a>
{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% block content %}
{% load my_tags %}
    <form class="form-horizontal" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ register_form.as_ul }}
    <br>
    <input class="form-control" type="submit" value="Регистрация">
    </form>
    <a class="btn btn-link" href="{% url 'auth:login' %}">вход</a>
        <div>{{ message }}</div>
        <div>{{ conf_code }}</div>
{% endblock %}

authapp/templates/authapp/verification.html
{% extends 'authapp/base.html' %}
{% load static %}


{% block content %}

  {% if user.is_authenticated %}
    <h3>Поздравляем!</h3>
    <br>
    <h4>Пользователь {{user.username}} подтвержден.</h4>
  {% else %}
    <h3>Верификация не пройдена.</h3>
  {% endif %}
  <br>
  <button class="btn btn-round form-control">
    <a href="{% url 'main' %}" class="">на главную</a>
  </button>

{% endblock %}