adminapp/urls.py
from django.urls import path


import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    # path('users/create/', adminapp.user_create, name='user_create'),
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),

    # path('users/read/', adminapp.users, name='users'),
    path('users/read/<page>/', adminapp.UsersListView.as_view(), name='users'),

    # path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),

    # path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    # path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),

    # path('categories/read/<page>/', adminapp.categories, name='categories'),
    path('categories/read/<page>/', adminapp.ProductCategoriesListView.as_view(), name='categories'),

    # path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),

    # path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),
    path('categories/delete/<int:pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    # path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),

    # path('products/read/category/<int:pk>/<page>', adminapp.products, name='products'),
    path('products/read/category/<int:pk>/<page>/', adminapp.ProductsListView.as_view(), name='products'),

    # path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),

    # path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),

    # path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),

    path('orders/read/<page>/', adminapp.OrdersListView.as_view(), name='orders'),

    # path('orders/read/<pk>/<status>/', adminapp.order_edit, name='order_edit'),
    path('orders/read/<pk>/<status>/', adminapp.OrderEditStatusView.as_view(), name='order_edit'),
]

authapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),

    path('edit/', authapp.edit, name='edit'),
    # path('edit/', authapp.UserEditUpdateView.as_view(), name='edit'),

    path('verify/<email>/<activation_key>/', authapp.verify, name='verify'),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

import mainapp.views as mainapp

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    # path('', mainapp.main, name='main'),
    path('', mainapp.MainListView.as_view(), name='main'),

    # path('about/', mainapp.about, name='about'),
    path('about/', mainapp.AboutTemplateView.as_view(), name='about'),

    # path('google7802449c7f174ab1.html/', mainapp.GoogleTemplateView.as_view(), name='google'),

    # path('service/', mainapp.service, name='service'),
    path('service/', mainapp.ServiceTemplateView.as_view(), name='service'),

    path('gallery/', include('mainapp.urls', namespace='gallery')),

    # path('news/', mainapp.news, name='news'),
    path('news/', mainapp.NewsTemplateView.as_view(), name='news'),

    # path('team/', mainapp.team, name='team'),
    path('team/', mainapp.TeamTemplateView.as_view(), name='team'),

    # path('contacts/', mainapp.contacts, name='contacts'),
    path('contacts/', mainapp.ContactsListView.as_view(), name='contacts'),

    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),

    path('', include('social_django.urls', namespace='social')),

    path('order/', include('ordersapp.urls', namespace='order')),

    path('admin/', include('adminapp.urls', namespace='admin')),
    # path('admin/', admin.site.urls, name='admin'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

ordersapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
import ordersapp.views as ordersapp


app_name = 'ordersapp'

urlpatterns = [
    path('', ordersapp.OrderListView.as_view(), name='orders_list'),
    path('create/', ordersapp.OrderItemsCreateView.as_view(), name='order_create'),
    path('read/<pk>/', ordersapp.OrderItemsReadView.as_view(), name='order_read'),
    path('update/<pk>/', ordersapp.OrderItemsUpdateView.as_view(), name='order_update'),
    path('delete/<pk>/', ordersapp.OrderItemsDeleteView.as_view(), name='order_delete'),
    path('forming/<pk>/', ordersapp.order_forming_complete, name='order_forming_complete'),
    path('create/edit/<int:pk>/<quantity>/', ordersapp.OrderUpdateView.as_view(), name='order_edit'),

    path('product/<pk>/price/', ordersapp.get_product_price_quantity),
]

adminapp/models.py
from django.db import models

# Create your models here.

ordersapp/models.py
from django.conf import settings
from django.db import models

from mainapp.models import Games


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    DONE = 'DN'
    CANCEL = 'CNC'

    ORDER_STATUSES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'обрабатывается'),
        (PROCEEDED, 'обработан'),
        (PAID, 'оплачен'),
        (READY, 'готов к выдаче'),
        (DONE, 'выдан'),
        (CANCEL, 'отменен')
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Пользователь')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    status = models.CharField(max_length=3, choices=ORDER_STATUSES,  verbose_name='Статус заказа', default=FORMING)
    is_active = models.BooleanField(default=True, verbose_name='Активен', db_index=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'Заказ №{self.id}'

    # @property
    # def get_total_quantity(self):
    #     items = self.orderitems.select_related()
    #     return sum(list(map(lambda x: x.quantity, items)))

    @property
    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    # @property
    # def get_total_cost(self):
    #     items = self.orderitems.select_related()
    #     return sum(list(map(lambda x: x.quantity * x.product.price, items)))

    @property
    def get_summary(self):
        items = self.orderitems.select_related()
        total_quantity = sum(list(map(lambda x: x.quantity, items)))
        total_cost = sum(list(map(lambda x: x.quantity * x.product.price, items)))
        return {
            'total_quantity': total_quantity,
            'total_cost': total_cost
        }

    def delete(self):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.product.save()

        self.is_active = False
        self.save()

    # def get_statuses_list(self):
    #     statuses = []
    #     for status in self.ORDER_STATUSES:
    #         self.statuses.append(status[1])
    #     return statuses


# class OrderItemQuerySet(models.QuerySet):
#     def delete(self, *args, **kwargs):
#         for object in self:
#             object.product.quantity += object.quantity
#             object.product.save()
#         super().delete(*args, **kwargs)


class OrderItem(models.Model):
    # objects = OrderItemQuerySet.as_manager()

    order = models.ForeignKey(Order, related_name='orderitems', on_delete=models.CASCADE, verbose_name='Заказ')
    product = models.ForeignKey(Games, on_delete=models.CASCADE, verbose_name='Продукт')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.get(pk=pk)

    @property
    def get_product_cost(self):
        return self.product.price * self.quantity

    # def save(self, *args, **kwargs):
    #     if self.pk:
    #         self.product.quantity -= self.quantity - self.__class__.get_item(self.pk).quantity
    #     else:
    #         self.product.quantity -= self.quantity
    #     self.product.save()
    #     super().save(*args, **kwargs)

    # def delete(self, *args, **kwargs):
    #     self.product.quantity += self.quantity
    #     self.product.save()
    #     super().delete(*args, **kwargs)

adminapp/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from authapp.forms import ShopUserEditForm
from authapp.models import ShopUser
from mainapp.models import GameCategories, Games


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductCategoryEditForm(forms.ModelForm):
    discount = forms.IntegerField(label='скидка', required=False, min_value=0, max_value=90, initial=0)

    class Meta:
        model = GameCategories
        # fields = '__all__'
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(ProductCategoryEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = "form-control"


class GameReadForm(forms.ModelForm):
    class Meta:
        model = Games
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(GameReadForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = "form-control"


class GameEditForm(forms.ModelForm):
    class Meta:
        model = Games
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(GameEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = "form-control"

adminapp/templates/adminapp/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    <link rel="shortcut icon" href="">
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'style/style-admin.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'style/css/bootstrap.min.css' %}">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&family=Roboto+Condensed:wght@300;400&display=swap" rel="stylesheet">
        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/png">
    {% endblock %}

    {% block js %}
            <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
{#            <script src = "{% static 'js/jquery-3.2.1.min.js' %}"></script>#}
{#            <script src = "{% static 'js/admin_order_scripts.js' %}"></script>#}
    {% endblock %}
</head>
<body>
  <div class="{% if request.resolver_match.url_name == 'orders' %} order_container {% else %} admin_container {% endif %} ">
    <div class="h2 text-center head">
      Админка
    </div>
    {% block menu %}
      <div class="admin_menu">
        {% include 'adminapp/includes/inc_menu.html' %}
      </div>
    {% endblock %}

    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="categories_list">
    <button class="new_category">
      <a href={% url 'admin:category_create' %}>
        новая категория
      </a>
    </button>


    <div class="paginator">
      {% if page_obj.has_previous %}
        <a href="{% url 'admin:categories' page_obj.previous_page_number %}"><</a>
      {% endif %}
      <span class="current"> страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</span>
      {% if page_obj.has_next %}
        <a href="{% url 'admin:categories' page_obj.next_page_number %}">></a>
      {% endif %}
    </div>


    {% for object in object_list %}
      <div class="category_record {% if not object.is_active %}not_active{% endif %}">
        <div class="category_name">
          {{ object.name|title }}
        </div>
        <div class="category_actions">
          <button>
            <a href={% url 'admin:products' object.pk 1 %}>
              товары категории
            </a>
          </button>
          <button>
            <a href={% url 'admin:category_update' object.pk %}>
              редактировать
            </a>
          </button>
          <button>
            <a href={% url 'admin:category_delete' object.pk %}>
              {% if object.is_active %} удалить {% else %} восстановить {% endif %}
            </a>
          </button>
        </div>
        <div class="category_desc">
          {{ object.description|title }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}

adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="category_delete">
        {% if object.is_active %}
            Уверены, что хотите удалить категорию <strong>{{ object.name }}</strong>?
        {% else %}
            Уверены, что хотите восстановить категорию <strong>{{ object.name }}</strong>?
        {% endif %}
      <form action="{% url 'admin:category_delete' object.pk %}"
            method="post">
        {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="{% if object.is_active %}удалить{% else %}восстановить{% endif %}">
      </form>
      <button class="btn btn-success">
        <a href="{% url 'admin:categories' 1 %}">
          Отмена
        </a>
      </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin:categories' 1 %}">
      к списку категорий
    </a>
  </button>
{% endblock %}

adminapp/templates/adminapp/orders.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}


{% block content %}
    <table class="table orders_list">
        <thead>
            <tr>
                <th>ID</th>
                <th>Пользователь</th>
                <th>Создан</th>
                <th>Обновлен</th>
                <th>Статус</th>
            </tr>
        </thead>
        <tbody>
            <div class="users_list">
                <button class="new_user">
                    <a href="{% url 'order:order_create' %}">
                    новый заказ
                    </a>
                </button>
                <div class="paginator">
                    {% if page_obj.has_previous %}
                        <a href="{% url 'admin:orders' page_obj.previous_page_number %}"><</a>
                    {% endif %}
                    <span class="current"> страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</span>
                    {% if page_obj.has_next %}
                        <a href="{% url 'admin:orders' page_obj.next_page_number %}">></a>
                    {% endif %}
                </div>
                {% for item in object_list %}
                    <tr>
                        <td class="td1 orders_list">{{ item.pk }}</td>
                        <td>{{ item.user }}</td>
                        <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                        <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                        <td>
                            <div class="dropdown">
                                <a class="dropdown-toggle menu-link" href="#" data-toggle="dropdown">
                                    {{ item.get_status_display }}
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    {% for status in statuses %}
                                        <li>
                                            <a name="{{ item.pk }}" class="menu-link"  href="{% url 'admin:order_edit' item.pk status %}">
                                            {{ status }}
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </td>
                        <td>
                            <a href="{% url 'ordersapp:order_read' item.pk %}">
                            посмотреть
                            </a>
                        </td>
                        <td>
                            {% if item.status == 'FM' %}
                                <a href="{% url 'ordersapp:order_update' item.pk %}">
                                редактировать
                                </a>
                            {% endif %}
                        </td>
                        <td>
                            {% if item.status == 'FM' %}
                                <a href="{% url 'ordersapp:order_delete' item.pk %}">
                                удалить
                                </a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </div>
        </tbody>
    </table>
{% endblock %}

adminapp/templates/adminapp/product.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
<div class="media">
  <img src="{{ object.image|media_folder_products }}" class="align-self-end mr-3" alt="{{ objects.name }}">
  <div class="media-body">
    <h5 class="mt-0">{{ object.game_category|upper }}</h5>
    <div><span class="section_header">Название:</span> {{ object.name }}</div>
    <div><span class="section_header">Описание:</span> {{ object.description }}</div>
    <div><span class="section_header">Цена:</span> {{ object.price }}&#36;</div>
    <div><span class="section_header">Количество:</span> {{ object.quantity }}</div>
  </div>
</div>
<button type="button" class="btn btn-secondary btn-lg btn-block"><a href="{% url 'admin:products' game_category.pk 1 %}">
      к списку игр категории
    </a></button>
{% endblock %}

adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="category_delete">
        {% if object.is_active %}
            Уверены, что хотите удалить игру <strong>{{ object.name }}</strong>?
        {% else %}
            Уверены, что хотите восстановить игру <strong>{{ object.name }}</strong>?
        {% endif %}
      <form action="{% url 'admin:product_delete' object.pk %}"
            method="post">
        {% csrf_token %}
        {% if object.is_active %}
            <input class="btn btn-danger" type="submit" value="удалить">
          {% else %}
            <input class="btn btn-danger" type="submit" value="восстановить">
          {% endif %}
      </form>
      <button class="btn btn-success">
        <a href="{% url 'admin:products' object.game_category.pk 1 %}">
          Отмена
        </a>
      </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin:products' game_category.pk 1 %}">
      к списку игр категории
    </a>
  </button>
{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
  <span class="category_name">Категория: {{ game_category.name|upper }}</span>
  <div class="products_list">
    <button class="new_product">
      <a href={% url 'admin:product_create' game_category.pk %}>
        новый продукт
      </a>
    </button>

    <div class="paginator">
      {% if page_obj.has_previous %}
        <a href="{% url 'admin:products' game_category.pk page_obj.previous_page_number %}"><</a>
      {% endif %}
      <span class="current"> страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</span>
      {% if page_obj.has_next %}
        <a href="{% url 'admin:products' game_category.pk page_obj.next_page_number %}">></a>
      {% endif %}
    </div>


    {% for object in object_list %}
      <div class="product_record {% if not object.is_active %}not_active{% endif %}">
        <img 
          src="{{object.image|media_folder_products}}"
          alt="{{ object.name }}">
        <div class="product_name">
          {{ object.name|title }}
        </div>
        <div class="product_actions">
          <button>
            <a href={% url 'admin:product_read' object.pk %}>
              подробнее
            </a>
          </button>
          <button>
            <a href={% url 'admin:product_update' object.pk %}>
              редактировать
            </a>
          </button>
          <button>
            <a href={% url 'admin:product_delete' object.pk %}>
              {% if object.is_active %} удалить {% else %} восстановить {% endif %}
            </a>
          </button>
        </div>
        <div class="summary">
          <b>цена</b>
          <p>{{ object.price }}&#36;</p>
          <b>количество</b>
          <p>{{ object.quantity }}</p>
        </div>
        <div class="product_desc">
          {{ object.short_desc|title }}
        </div>
      </div>
    {% endfor%}
  </div>
  <a  href="{% url 'admin:categories' 1 %}" class ="btn btn-round btn-success">К категориям</a>
{% endblock %}

adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
  <div class="user_delete">
    {% if object.is_active %}
    Уверены, что хотите удалить
    {% else %}
    Уверены, что хотите восстановить
    {% endif %}{{ object.username }}
    {% if object.first_name %}
      ({{ object.first_name|title }}</b>
      {% if object.last_name %}
        {{ object.last_name|title }}
      {% endif %})
    {% endif %}
    ?
    <form action="{% url 'admin:user_delete' object.pk %}"
          method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="{% if object.is_active %}удалить{% else %}восстановить{% endif %}">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin:users' 1 %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin:users' 1 %}">
      к списку пользователей
    </a>
  </button>
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
  <div class="users_list">
    <button class="new_user">
      <a href={% url 'admin:user_create' %}>
        новый пользователь
      </a>
    </button>
    <div class="paginator">
      {% if page_obj.has_previous %}
        <a href="{% url 'admin:users' page_obj.previous_page_number %}"><</a>
      {% endif %}
      <span class="current"> страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</span>
      {% if page_obj.has_next %}
        <a href="{% url 'admin:users' page_obj.next_page_number %}">></a>
      {% endif %}
    </div>

    {% for object in object_list %}
      <div
       class="user_record {% if not object.is_active %}not_active{% endif %}">
        <img
          src="{{ object.avatar|media_folder_users }}"
          alt="{{ object.username }}">
        <div class="user_role">
          {% if object.is_superuser %}
            администратор
          {% else %}
            пользователь
          {% endif %}
          <button>
            <a href={% url 'admin:user_update' object.pk %}>
              редактировать
            </a>
          </button>
          <button>
            <a href={% url 'admin:user_delete' object.pk %}>
              {% if object.is_active %} удалить {% else %} восстановить {% endif %}
            </a>
          </button>
        </div>
        <div class="user_name">
          <p><strong>{{ object.username }}</strong></p>
	    <p>
            {% if object.first_name %}
              <b>{{ object.first_name|title }}</b>
                {% if object.last_name %}
                  <p>{{ object.last_name|title }}</p>
                {% endif %}
            {% endif %}
          </p>
        </div>
        <div class="user_age">
          age:<br>
          {{ object.age }} лет
        </div>
        <div class="user_email">
          email:<br>
          {{ object.email }}
        </div>
        <div class="user_lastlogin">
          logged:<br>
          {{ object.last_login }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}