authapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),

    path('edit/', authapp.edit, name='edit'),
    # path('edit/', authapp.UserEditUpdateView.as_view(), name='edit'),

    path('verify/<email>/<activation_key>/', authapp.verify, name='verify'),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

import mainapp.views as mainapp

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    # path('', mainapp.main, name='main'),
    path('', mainapp.MainListView.as_view(), name='main'),

    # path('about/', mainapp.about, name='about'),
    path('about/', mainapp.AboutTemplateView.as_view(), name='about'),

    # path('google7802449c7f174ab1.html/', mainapp.GoogleTemplateView.as_view(), name='google'),

    # path('service/', mainapp.service, name='service'),
    path('service/', mainapp.ServiceTemplateView.as_view(), name='service'),

    path('gallery/', include('mainapp.urls', namespace='gallery')),

    # path('news/', mainapp.news, name='news'),
    path('news/', mainapp.NewsTemplateView.as_view(), name='news'),

    # path('team/', mainapp.team, name='team'),
    path('team/', mainapp.TeamTemplateView.as_view(), name='team'),

    # path('contacts/', mainapp.contacts, name='contacts'),
    path('contacts/', mainapp.ContactsListView.as_view(), name='contacts'),

    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),

    path('', include('social_django.urls', namespace='social')),

    path('order/', include('ordersapp.urls', namespace='order')),

    path('admin/', include('adminapp.urls', namespace='admin')),
    # path('admin/', admin.site.urls, name='admin'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

ordersapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
import ordersapp.views as ordersapp


app_name = 'ordersapp'

urlpatterns = [
    path('', ordersapp.OrderListView.as_view(), name='orders_list'),
    path('create/', ordersapp.OrderItemsCreateView.as_view(), name='order_create'),
    path('read/<pk>/', ordersapp.OrderItemsReadView.as_view(), name='order_read'),
    path('update/<pk>/', ordersapp.OrderItemsUpdateView.as_view(), name='order_update'),
    path('delete/<pk>/', ordersapp.OrderItemsDeleteView.as_view(), name='order_delete'),
    path('forming/<pk>/', ordersapp.order_forming_complete, name='order_forming_complete'),
    path('create/edit/<int:pk>/<quantity>/', ordersapp.OrderUpdateView.as_view(), name='order_edit'),

    path('product/<pk>/price/', ordersapp.get_product_price_quantity),
]

ordersapp/models.py
from django.conf import settings
from django.db import models

from mainapp.models import Games


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    DONE = 'DN'
    CANCEL = 'CNC'

    ORDER_STATUSES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCEED, 'обрабатывается'),
        (PROCEEDED, 'обработан'),
        (PAID, 'оплачен'),
        (READY, 'готов к выдаче'),
        (DONE, 'выдан'),
        (CANCEL, 'отменен')
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Пользователь')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    status = models.CharField(max_length=3, choices=ORDER_STATUSES,  verbose_name='Статус заказа', default=FORMING)
    is_active = models.BooleanField(default=True, verbose_name='Активен', db_index=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'Заказ №{self.id}'

    # @property
    # def get_total_quantity(self):
    #     items = self.orderitems.select_related()
    #     return sum(list(map(lambda x: x.quantity, items)))

    @property
    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    # @property
    # def get_total_cost(self):
    #     items = self.orderitems.select_related()
    #     return sum(list(map(lambda x: x.quantity * x.product.price, items)))

    @property
    def get_summary(self):
        items = self.orderitems.select_related()
        total_quantity = sum(list(map(lambda x: x.quantity, items)))
        total_cost = sum(list(map(lambda x: x.quantity * x.product.price, items)))
        return {
            'total_quantity': total_quantity,
            'total_cost': total_cost
        }

    def delete(self):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.product.save()

        self.is_active = False
        self.save()

    # def get_statuses_list(self):
    #     statuses = []
    #     for status in self.ORDER_STATUSES:
    #         self.statuses.append(status[1])
    #     return statuses


# class OrderItemQuerySet(models.QuerySet):
#     def delete(self, *args, **kwargs):
#         for object in self:
#             object.product.quantity += object.quantity
#             object.product.save()
#         super().delete(*args, **kwargs)


class OrderItem(models.Model):
    # objects = OrderItemQuerySet.as_manager()

    order = models.ForeignKey(Order, related_name='orderitems', on_delete=models.CASCADE, verbose_name='Заказ')
    product = models.ForeignKey(Games, on_delete=models.CASCADE, verbose_name='Продукт')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.get(pk=pk)

    @property
    def get_product_cost(self):
        return self.product.price * self.quantity

    # def save(self, *args, **kwargs):
    #     if self.pk:
    #         self.product.quantity -= self.quantity - self.__class__.get_item(self.pk).quantity
    #     else:
    #         self.product.quantity -= self.quantity
    #     self.product.save()
    #     super().save(*args, **kwargs)

    # def delete(self, *args, **kwargs):
    #     self.product.quantity += self.quantity
    #     self.product.save()
    #     super().delete(*args, **kwargs)

ordersapp/forms.py
from django import forms

from mainapp.models import Games
from ordersapp.models import Order, OrderItem


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemForm(forms.ModelForm):

    price = forms.CharField(label='цена за единицу', required=False)
    quantity_storage = forms.IntegerField(label='Количество на складе', required=False)

    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

        self.fields['product'].queryset = Games.get_items()

ordersapp/views.py
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import F
from django.db.models.signals import pre_save, pre_delete
from django.dispatch import receiver
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from basketapp.models import Basket
from mainapp.models import Games
from ordersapp.forms import OrderItemForm
from ordersapp.models import Order, OrderItem
from django.db import models
from django.template.loader import render_to_string
from django.http import HttpResponseRedirect, JsonResponse, request


class OrderListView(ListView):
    model = Order

    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user, is_active=True)

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = 'заказы'
        return context_data


class OrderItemsCreateView(CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('order:orders_list')

    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context_data = super(OrderItemsCreateView, self).get_context_data(**kwargs)
        context_data['title'] = 'создание заказа'
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            basket_item = Basket.get_items(self.request.user)
            print(f'REQUEST: {self.request}')
            if len(basket_item):
                OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=len(basket_item))
                formset = OrderFormSet()
                for num, form in enumerate(formset.forms):
                    form.initial['product'] = basket_item[num].product
                    form.initial['quantity'] = basket_item[num].quantity
                    form.initial['price'] = basket_item[num].product.price
                    form.initial['quantity_storage'] = basket_item[num].product.quantity
            else:
                formset = OrderFormSet()

        context_data['orderitems'] = formset

        return context_data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            Basket.get_items(self.request.user).delete()
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        if self.object.get_summary['total_cost'] == 0:
            self.object.delete()

        return super(OrderItemsCreateView, self).form_valid(form)


class OrderItemsUpdateView(UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy('order:orders_list')

    def get_context_data(self, **kwargs):
        context_data = super(OrderItemsUpdateView, self).get_context_data(**kwargs)
        context_data['title'] = 'редактирование заказа'
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST, instance=self.object)
        else:
            formset = OrderFormSet(instance=self.object)
            for form in formset:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price
                    form.initial['quantity_storage'] = form.instance.product.quantity
        context_data['orderitems'] = formset
        return context_data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']
        self.object = form.save()
        if orderitems.is_valid():
            orderitems.instance = self.object
            orderitems.save()

        if self.object.get_summary['total_cost'] == 0:
            self.object.delete()

        return super(OrderItemsUpdateView, self).form_valid(form)


class OrderItemsDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy('order:orders_list')

    def get_context_data(self, **kwargs):
        context_data = super(OrderItemsDeleteView, self).get_context_data(**kwargs)
        context_data['title'] = 'удаление заказа'
        return context_data


class OrderItemsReadView(DetailView):
    model = Order

    def get_context_data(self, **kwargs):
        context_data = super(OrderItemsReadView, self).get_context_data(**kwargs)
        context_data['title'] = 'просмотр заказа'
        return context_data


def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()
    return HttpResponseRedirect(reverse('order:orders_list'))


@receiver(pre_save, sender=OrderItem)
@receiver(pre_save, sender=Basket)
def product_quantity_update_save(sender, update_fields, instance, **kwargs):
    print('*'*100)
    if update_fields is 'quantity' or 'product':
        if instance.pk:
            # instance.product.quantity -= instance.quantity - sender.get_item(instance.pk).quantity
            instance.product.quantity = F('quantity') - (instance.quantity - sender.get_item(instance.pk).quantity)
        else:
            # instance.product.quantity -= instance.quantity
            instance.product.quantity = F('quantity') - instance.quantity
        instance.product.save()


@receiver(pre_delete, sender=OrderItem)
@receiver(pre_delete, sender=Basket)
def product_quantity_update_delete(sender, instance, **kwargs):
    # instance.product.quantity += instance.quantity
    instance.product.quantity = F('quantity') + instance.quantity
    instance.product.save()


def get_product_price_quantity(request, pk):
    if request.is_ajax():
        product = Games.objects.filter(pk=int(pk)).first()
        if product:
            return JsonResponse({'price': product.price, 'quantity_storage': product.quantity})
        else:
            return JsonResponse({'price': 0, 'quantity_storage': 0})


class OrderUpdateView(UpdateView):
    model = Order
    template_name = 'ordersapp/order_form.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(OrderUpdateView, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        if request.is_ajax():
            quantity = int(self.kwargs.get('quantity', None))
            game_item_pk = self.kwargs.get('pk', None)
            print(f'Quantity: {quantity}\nGame_item_pk: {game_item_pk}')
            new_game_item = Games.get_item(game_item_pk)
            if quantity > 0:
                new_game_item.quantity = quantity
                new_game_item.save()
            else:
                new_game_item.delete()
            order_items = Order.objects.filter(user=request.user)
            content = {
                'object_list': order_items,
                'user': request.user,
            }

            result = render_to_string('ordersapp/order_form.html', content)

            return JsonResponse({'result': result})



ordersapp/templates/ordersapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8">
  <title>
       {% block title %}
           {{ title|title }}
       {% endblock %}
   </title>
    <link rel="shortcut icon" href="">
   {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'style/style-order.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'style/css/bootstrap.min.css' %}">
        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/png">
   {% endblock %}
   {% block js %}
       <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
       <script src="{% static 'js/jquery.formset.js' %}"></script>
       <script src="{% static 'js/orders_scripts.js' %}"></script>
   {% endblock %}
</head>
<body>
  <div class="order_container">
       {% block content %}

       {% endblock %}

  </div>
</body>
</html>

ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends 'ordersapp/base.html' %}
{% load static %}

{% block content %}
   <div class="category_delete">
       <div class="h1">Уверены, что хотите удалить?</div>
       {% include 'ordersapp/includes/inc_order_summary.html' %}
       <form action="{% url 'ordersapp:order_delete' object.pk %}" method="post">
           {% csrf_token %}
           <input class="btn btn-danger" type="submit" value="удалить">
       </form>
       <button class="btn btn-success">
           <a href="{% url 'ordersapp:orders_list' %}">отмена</a>
       </button>
   </div>
{% endblock %}

ordersapp/templates/ordersapp/order_detail.html
{% extends "ordersapp/base.html" %}
{% load static %}
{% load my_tags %}

{% block content %}
   {% include 'ordersapp/includes/inc_order_summary.html' %}
   <div class="basket_list">
       {% for item in object.orderitems.select_related %}
           <div class="basket_record">
               <img src="{{ item.product.image|media_folder_products }}"
                    alt="{{ item.product.short_desc }}">
               <span class="category_name">
                   {{ item.product.category.name }}
               </span>
               <span class="product_name">{{ item.product.name }}</span>
               <span class="product_price">
                   {{ item.product.price }}&#36;
               </span>
               <span class="product_quantitiy">
                   x {{ item.quantity }} шт.
               </span>
               <span class="product_cost">
                    = {{ item.get_product_cost }}&#36;
               </span>
           </div>
       {% endfor %}
   </div>
   {% include 'ordersapp/includes/inc_order_actions.html' %}

{% endblock %}

ordersapp/templates/ordersapp/order_form.html
{% extends "ordersapp/base.html" %}
{% load static %}

{% block content %}
    {% include 'ordersapp/includes/inc_order_summary.html' %}
    <div class="order_form">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <table class="table">
                {{ orderitems.management_form }}
                {% for form in orderitems.forms %}
                    {% if forloop.first %}
                        <thead>
                            <tr>
                                {% for field in form.visible_fields %}
                                    <th class="{% cycle 'td1' 'td2' 'td3' 'td4' 'td5' %} order formset_td">
                                    {% if field.name == 'price' %}
                                        {{ field.label|capfirst }}, &#36;
                                    {% else %}
                                        {{ field.label|capfirst }}
                                    {% endif %}
                                    </th>
                                {% endfor %}
                            </tr>
                        </thead>
                    {% endif %}
                    <tr class="formset_row">
                        {% for field in form.visible_fields %}
                            <td class="{% cycle 'td1' 'td2' 'td3' 'td4' 'td5' %} order formset_td ">
                                {% if forloop.first %}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}
                                {% if field.name == 'quantity_storage' %}
                                    {% if field.value %}
                                        <span class="orderitems-{{ forloop.parentloop.counter0 }}-price">{{ field.value }}</span>
                                    {% endif %}
                                {% else %}
                                    {% if field.name == 'price' %}
                                        {% if field.value %}
                                            <span class="orderitems-{{ forloop.parentloop.counter0 }}-price">{{ field.value }}</span>
                                        {% endif %}
                                    {% else %}
                                        {{ field }}
                                    {% endif %}
                                {% endif %}
                                {% if field.name == 'quantity' %}
                                    {{ field.value.get_total_quantity }}
                                {% endif %}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
            <button type="submit" value="сохранить" class="btn btn-default btn-round form-control last">сохранить</button>
            {% include 'ordersapp/includes/inc_order_actions.html' %}
        </form>
    </div>
{% endblock %}




ordersapp/templates/ordersapp/order_list.html
{% extends 'ordersapp/base.html' %}
{% load static %}


{% block content %}
   <div class="h2 text-center head">
       Ваши заказы, 
       {% if user.first_name %}
           {{ user.first_name|title}}
       {% else %}
           Пользователь
       {% endif %}
   </div>
   <table class="table orders_list">
       <thead>
         <tr>
           <th>ID</th>
           <th>Создан</th>
           <th>Обновлен</th>
           <th>Статус</th>
         </tr>
       </thead>
       <tbody>
           {% for item in object_list %}
               <tr>
                   <td class="td1 orders_list">{{ item.pk }}</td>
                   <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                   <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                   <td>{{ item.get_status_display }}</td>
                   <td>
                       <a href="{% url 'ordersapp:order_read' item.pk %}">
                           посмотреть
                       </a>
                   </td>
                   <td>
                       {% if item.status == 'FM' %}
                         <a href="{% url 'ordersapp:order_update' item.pk %}">
                           редактировать
                         </a>
                       {% endif %}
                   </td>
                   <td>
                       {% if item.status == 'FM' %}
                         <a href="{% url 'ordersapp:order_delete' item.pk %}">
                             удалить
                         </a>
                       {% endif %}
                   </td>
               </tr>
           {% endfor %}
       </tbody>
   </table>
   <button class="btn btn-outline-success btn-round">
       <a href="{% url 'main' %}">
           на главную
       </a>
   </button>
   <button class="btn btn-outline-success btn-round">
       <a href="{% url 'ordersapp:order_create' %}">
           новый
       </a>
   </button>
{% endblock %}